### ISSUE TITLE
releay status

### ISSUE THREAD

**Issue by victron** [Brokly/ESPHome-Thermostate-Moes-BHT-002#10]
Добрый День,
Спасибо, за проделаную работу!

Возможно добавить binary sensor состояния реле (вкл/выкл.), в режиме авто.
Хочется видеть в статистике когда обогреватель включался.

**Comment by Brokly** [comment]
Привет ! Это и так видно в виджете климата. Если нужен такой сенсор , то это стоит сделать в конфиге вашего устройства. Есть бОльшая проблема связанная с этим вопросом.  Термостат не дает информации модулю есп о состоянии реле. В ветке dev ( https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/tree/dev ) описана доработка для получения истинного состояния, без нее эти данные синтезированы программно  и очень приблезительные.
