### ISSUE TITLE
recommended replace to esp32 c3 12f

### ISSUE THREAD

**Issue by tiimsvk** [Brokly/ESPHome-Thermostate-Moes-BHT-002#13]
if someone replaces the original mcu with another esp, I recommend esp32 c3 12f with bluetooth support

**Comment by Brokly** [comment]
Why replace?

**Comment by tiimsvk** [comment]
Because this chip from the esp32 series also supports bluetooth reception of signals and since I have several temperature sensors in rooms with bluetooth, it was an obvious choice. Or if someone would like more pins available than the esp8266 itself or the original one from tuya support.
