### ISSUE TITLE
Синхронизация времени

### ISSUE THREAD

**Issue by mrcoolyok** [Brokly/ESPHome-Thermostate-Moes-BHT-002#16]
Добрый день!
Подскажите, как то можно настройками поправить корректность синхронизации времени?
При включении каждый раз выдает время -10 часов от моего текущего

**Comment by Brokly** [comment]
Установить правильный источник времени. 
Например:
time:
  - platform: homeassistant
    id: sync_time

ИЛИ

time:
  - platform: sntp
    id: sync_time
    timezone: UTC+10  #подберите зону здесь, но это костыль

Больше информации :  https://esphome.io/components/time/index.html

**Comment by mrcoolyok** [comment]
Спасибо вам!
