### ISSUE TITLE
Как воспользоваться?

### ISSUE THREAD

**Issue by votarum** [Brokly/ESPHome-Thermostate-Moes-BHT-002#2]
Здравствуйте! Что-то не соображу, как воспользоваться вашей разработкой. С конфигами все понятно, а что делать с папочкой my_components/tuya_termo? Куда ее положить, чтобы содержимое подтянулось при сборке прошивки в ESPHome?

**Comment by Brokly** [comment]
В ту же папку где лежит ваш конфиг (yaml).
