### ISSUE TITLE
На TYWE3S OTA не работает, если board: esp_wroom_02

### ISSUE THREAD

**Issue by votarum** [Brokly/ESPHome-Thermostate-Moes-BHT-002#3]
На TYWE3S OTA не работает, если board: esp_wroom_02. Заменил на board: esp01_1m, снова прошил через UART, OTA работает. Аналогичная проблема описана [здесь](https://github.com/esphome/issues/issues/970), и [здесь](https://github.com/esphome/issues/issues/1006).

**Comment by Brokly** [comment]
Этот вопрос не ко мне. Вам сюда https://github.com/esphome/issues/issues

**Comment by Brokly** [comment]
Проверил свой конфиг, у меня там, как раз установлена, esp_wroom_02, при этом все работает. Видимо ваш модуль имеет всего 1 мегабайт флеша. Не могли бы вы показать фото вашей платы термостата и фото используемого на ней модуля esp  
? Вы уверены, что это TYWE3S ?

**Comment by votarum** [comment]
Модуль такой же как на фото у вас в readme. Устройство уже в работе, не смогу сфотографировать.

**Comment by Brokly** [comment]
В таком случае, для понимания вашей ошибки, имеет смысл использовать сенсор https://esphome.io/components/debug.html , для определения размера флешь памяти.
