### ISSUE TITLE
No Wifi symbol and problems with time syncing

### ISSUE THREAD

**Issue by MayorBug** [Brokly/ESPHome-Thermostate-Moes-BHT-002#4]
Thanks for adding additional features to your BHT-002 library. 

I have a older bht-002 with esp chip, but the clock doesn't stay in sync on that model. Some researching lead me to this: https://github.com/esphome/esphome/pull/3466

It seems like some models have added status pin for wifi connection and that also allows for time syncing. Unfortunately my model does not report a status pin. 

Do you have any idea to enable this wifi symbol on our units? 
![BHT-002-termostatas-baltas~2](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/assets/11988477/fd86bca9-1b62-4c92-99d3-63c3befcc125)
?

**Comment by Brokly** [comment]
It seems to me that you do not have time synchronization, because you did not specify the time source in the yaml config. Try adding in yaml config:
```yaml
time:
  - platform: sntp
    id: sync_time
```
As soon as there is time, I will try to figure out the Wi-Fi icon using the information you provided. Fnx.

**Comment by MayorBug** [comment]
I have the time component added. For me it does update only once while it first boots up (alfter restarting from circuit breaker). And then the time doesn't change after that. I am guessing my tuya chip expects the wifi connected flag to keep the time updated. I can provide supporting logs if needed

**Comment by Brokly** [comment]
I need more information. I have a thermostat on ESP32, but the clock there works with this version of the code.

I would like to see your logs. And I need to know the version of your thermostat. 

Do you need a pin that will change the level once per second? 

I seem to understand the situation. It will take me some time to finalize the code. I will not be able to verify the correctness of the edit, you will have to do it yourself.

**Comment by MayorBug** [comment]
BHT-002-GBLW, can't remember the year, but it is old. Probably first batch or something. Mine doesn't have gpio for network status. I just think it needs the report network status command, explained in the linked issue. 
[logs_bht-002-gblw_logs.txt](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/files/14434940/logs_bht-002-gblw_logs.txt)


I have attached a log, it there is any other debug output you need I can try to enable it.

**Comment by Brokly** [comment]
I fixed the mistake. It remains only to check. It seems that the problem was different.

**Comment by MayorBug** [comment]
Thank you for looking into it! I uploaded your latest code and took a longer log. I can see few "synchronized time" events. It can confirm on the weekend if it actually keeps time now, since I am not at that house currently. 
[logs_bht-002-gblw_run.txt](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/files/14446862/logs_bht-002-gblw_run.txt)

**Comment by Brokly** [comment]
I have the same thermostat, and it is also located in the village :) I don't see him at the moment. But I'll wait for your opinion.
Still, I don't like the log of your thermostat. I fixed another timeout, it should get better. Update the firmware.

**Comment by MayorBug** [comment]
This seems to be better, but here is a point in the log where the output changes. It seems to happen quite soon after: Cuclic auto restart protocol interchange 
[logs_bht-002-gblw_logs.txt](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/files/14448483/logs_bht-002-gblw_logs.txt)

**Comment by Brokly** [comment]
Yes, it's weird, I have exactly the same version of the thermostat, but yours stops sending temperature data after requesting general data. My thermostat behaves a little differently. It may be necessary to completely disable the reinitialization of the timer, in your case it is harmful. Made edits.

**Comment by MayorBug** [comment]
Looks like the code is more stable, but the device doesn't still update the clock. It has been stuck on 14:27 the whole day.. 
It has reached that time at some point, but then lost time. And in the log you can see clock sync at 19;19, but that isn't displayed on the thermostat.
[logs_bht-002-gblw_run.txt](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/files/14470209/logs_bht-002-gblw_run.txt)
![photo_2024-03-02_19-25-52](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/assets/11988477/2e440b5b-dbc1-46bc-9551-00a6f3257bef)

**Comment by Brokly** [comment]
Try this version - https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/tree/dev

**Comment by MayorBug** [comment]
Thank you for spending the time developing this further. I saw you have done quite many updates and also added the reset mod. Heating season is back and I am motivated to thinker with this device again. I tired the latest version, still no luck getting the time to sync on my device. 

Then I wanted to try to do the reset mod on my device, but the pcb layout is different. I located the dc/dc IC, but the chip is different and there is no documentation for it online so I am not sure to which pin I should solder the reset wire. We could probably assume the IC package pin layout is same as yours? 
![IMG_20241005_142922915](https://github.com/user-attachments/assets/80197cd5-9049-437c-950e-9143ad1a0c2b)
![IMG_20241005_143317125](https://github.com/user-attachments/assets/634e686c-3c9f-4be4-819a-8f82a685bdf3)

**Comment by tiimsvk** [comment]
have you tried that wifi icon?

**Comment by Brokly** [comment]
> have you tried that wifi icon?
The WI-Fi icon appears when the device is in the process of linking to your network. When used with ESPHOME firmware, there is simply no such mode. It is impossible to turn on or off the icon without mechanical modification of the device.

**Comment by Brokly** [comment]
> Then I wanted to try to do the reset mod on my device, but the pcb layout is different. I located the dc/dc IC, but the chip is different and there is no documentation for it online so I am not sure to which pin I should solder the reset wire. We could probably assume the IC package pin layout is same as yours?

It looks very much like your circuit uses the same DC/DC converters as other devices. But to be sure of this, you need to draw an electrical diagram. In addition, there are two such converters in the device. One of them supplies power to the Wi-Fi module (3.3 volts), the other to the thermostat processor (5 volts). It is necessary to reset the voltage by 5 volts. To do this, it is necessary to short-circuit pin No. 4 of the converter chip to GND for a short time.

**Comment by tiimsvk** [comment]
> > have you tried that wifi icon?
> > The WI-Fi icon appears when the device is in the process of linking to your network. When used with ESPHOME firmware, there is simply no such mode. It is impossible to turn on or off the icon without mechanical modification of the device.

How to mechanical modification of the device ?

**Comment by Brokly** [comment]
> How to mechanical modification of the device ?

Find the contact on the display that is responsible for the icon glowing.
Cut it off from the processor.
Connect to the Wi-Fi module and control it directly.

**Comment by MayorBug** [comment]
In the end I decided not to physically mod my device. The thermostat part works very well as it is. The time display isn't that critical for me.

**Comment by MayorBug** [comment]
Brokly have you seen this info? 
https://github.com/esphome/esphome/pull/7028

There is a mention that some devices need cloud connection flag to be "faked" before sending any data to turn the wifi icon through the Tuya MCU.

**Comment by MayorBug** [comment]
Brokly have you seen this info? 
https://github.com/esphome/esphome/pull/7028#issuecomment-2240319761

There is a mention that some devices need cloud connection flag to be "faked" before sending any data to enable the wifi icon through the Tuya MCU.

**Comment by MayorBug** [comment]
I tried setting in getNetSate() 
 status=wsWifiConf (to fake the connection status), 
And also in some other places 
But still the wifi icon did not light up. 

Also managed to capture one time sync from the logs. 

`[12:29:06][D][climate:396]: 'Thermostat' - Sending state:
[12:29:06][D][climate:399]:   Mode: HEAT
[12:29:06][D][climate:401]:   Action: IDLE
[12:29:06][D][climate:410]:   Preset: NONE
[12:29:06][D][climate:419]:   Current Temperature: 20.00°C
[12:29:06][D][climate:425]:   Target Temperature: 19.00°C
[12:29:22][D][TuyaTermo:920]: Get Date/time request
[12:29:22][D][TuyaTermo:634]: Send time 12:29:22 3/11/24 (dw:7)
[12:29:34][D][sensor:093]: 'Signal': Sending state -74.00000`

My device seems to only show the correct time when the Get Date/time request happens, after that it doesn't update

**Comment by MayorBug** [comment]
I tried setting in getNetSate() 
 status=wsWifiCloud (to fake the connection status), 
And also in some other places 
But still the wifi icon did not light up. 

Also managed to capture one time sync from the logs. 

`[12:29:06][D][climate:396]: 'Thermostat' - Sending state:
[12:29:06][D][climate:399]:   Mode: HEAT
[12:29:06][D][climate:401]:   Action: IDLE
[12:29:06][D][climate:410]:   Preset: NONE
[12:29:06][D][climate:419]:   Current Temperature: 20.00°C
[12:29:06][D][climate:425]:   Target Temperature: 19.00°C
[12:29:22][D][TuyaTermo:920]: Get Date/time request
[12:29:22][D][TuyaTermo:634]: Send time 12:29:22 3/11/24 (dw:7)
[12:29:34][D][sensor:093]: 'Signal': Sending state -74.00000`

My device seems to only show the correct time when the Get Date/time request happens, after that it doesn't update

**Comment by Brokly** [comment]
> I tried setting in getNetSate() status=wsWifiCloud (to fake the connection status), And also in some other places But still the wifi icon did not light up.

The WIFI icon appears only when the device is paired with the Tuya server. In this mode, the MCU of the thermostat does not provide information about operation. Therefore, you either show the icon or operate the thermostat. It is not possible to show the icon and control the operation of the thermostat at the same time.

**Comment by MayorBug** [comment]
Thanks! That makes sense. Then there is the time sync issue left to solve. So far after cold boot when the tuya MCU request time, the time updates. Usually the next minute it actually changes +1 minute and after that it reverts back to the time at the request moment. Then the time gets stuck for some reason. And the tuya mcu doesn't seem to ask for new time requests. 

I tried the send "time sync packets" every second option. That did not improve anything on my side. Maybe it is too frequent? I will try to edit the code to send time packets every minute. Maybe that will work. Altough I am starting to think that on my unit the tuca mcu doesn't accept time packets when it is not actually requesting them.

**Comment by Brokly** [comment]
The transmission of time data makes sense only at the request of the thermostat MCU. This is just the answer. Judging by the fact that the thermostat changes time and then stops, something is wrong with the RTC of the thermostat MCU.

**Comment by MayorBug** [comment]
Yeah, could be. Closing this issue for now
