### ISSUE TITLE
Не компилируется прошивка после обновления ESPHome 

### ISSUE THREAD

**Issue by mrcoolyok** [Brokly/ESPHome-Thermostate-Moes-BHT-002#9]
С обновлением ESPHome появилось обязательное требование к наличию параметра platform: esphome в разделе ota
То есть выглядеть раздел теперь должен так:
ota:
  **- platform: esphome**
    password: "xxxxxxxxxxxxxxxx"

При попытке комиляции и установки теперь ошибка, скрин во вложении
![2024-06-20_140932](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/assets/75407649/f1d8e946-6ac5-4481-8626-a2a7476f3712)

**Comment by mrcoolyok** [comment]
До добавления параметра ошибка такая:
![изображение](https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/assets/75407649/9dbe714a-03fe-41ca-864b-ea2817443113)

**Comment by Brokly** [comment]
Используйте старую версию ESPHOME, на данный момент не имею свободного времени для изучения проблемы. Думаю, такая ситуация продлится довольно долго.

Впрочем, можете попробовать не использовать 'mcu_reset_pin', просто удалите из конфига эту опцию.

**Comment by Brokly** [comment]
Все же нашел несколько минут. Возьмите код из DEV ветки ( https://github.com/Brokly/ESPHome-Thermostate-Moes-BHT-002/tree/dev ). Поправить то поправил, компилится, но как будет работать - не знаю. Проблема была в изменении обработки ОТА. Как я понял, разработчики разделили библиотеки для разных процессоров. Код термостата контролирует информацию о окончании прошивки для сброса счетчика перезагрузок по потери связи с процессором термостата, поэтому для правильного тестирования прошивки нужно залить ее два раза по ОТА. Если проблем не возникнет, то значит я внес правильные изменения. Но будьте осторожны, может получиться так, что, в случае ошибки, придется шить термостат проводами.
